title: Michael Phipps # your name (or website title) here
logo: "/image/WarriorsGame.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is a brief overview of a few projects and courses I have recently completed. 
  <br><br>
  Thanks for visiting
  <br><br>
  <a href="https://www.linkedin.com/in/mjphipps/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
